---
format: gfm
execute:
  echo: false
  message: false
  warning: false
editor: visual
editor_options: 
  chunk_output_type: console
---

# Smart System Education Platfrom
```{r setup, include=FALSE}
# Get the absolute file path
file_path <- fs::path_real("README.qmd")  # Adjust as needed for your file path
# Remove the first two folders
path_components <- strsplit(file_path, "/")[[1]]
shortened_path <- fs::path_join(path_components[-c(2, 3)])
```
## Location: `r shortened_path `

### Description
```{r, include=TRUE}
#| child: .READMEdescription.md
```


### Directories & Files

The repository has the following directory tree.

```{r}
fs::dir_tree(recurse = 1)
```

A short description of the directories can be found below.

```{r, include=FALSE}
# List all directories in the current folder
folders <- fs::dir_ls(path = ".", type = "directory")

# Loop through the directories and read the description.md file if it exists
for (folder in folders) {
  description_file <- fs::path(folder, "READMEdescription.md")
  
  # Check if description.md exists in the folder
  if (fs::file_exists(description_file)) {
    # Print the folder name as a header
    cat(paste("#### Description for", folder), "\n\n")
    
    # Read and print the content of description.md
    description_content <- readLines(description_file)
    cat(paste(description_content, collapse = "\n"), "\n\n")
  }
}

```