name: Render README.qmd to Markdown

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Find README.qmd Files
      id: find-files
      run: |
        files=$(find . -name "README.qmd")
        if [ -z "$files" ]; then
          echo "No README.qmd files found."
          exit 0
        fi
        echo "::set-output name=files::$files"
      shell: bash

    - name: Render Files
      if: steps.find-files.outputs.files != ''
      run: |
        for file in ${{ steps.find-files.outputs.files }}; do
          quarto render "$file" --to markdown
        done
