name: Render QMD Files

on:
  push:
    branches:
      - main  # Adjust as needed

jobs:
  render_qmd:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.269/quarto-1.2.269-linux-amd64.deb
        sudo dpkg -i quarto-1.2.269-linux-amd64.deb

    - name: Install R and Required Packages
      env:
        R_LIBS_USER: ~/R/library  # Define a writable library path
      run: |
        sudo apt-get update
        sudo apt-get install -y r-base
        mkdir -p "$R_LIBS_USER"  # Create the library path if it doesn't exist
        Rscript -e 'install.packages(c("rmarkdown", "jsonlite"), repos="https://cloud.r-project.org")'

    - name: Render README.qmd files to README.md
      run: |
        for file in $(find . -name 'README.qmd'); do
          # Render each README.qmd to README.md
          quarto render "$file" --to markdown
        done

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add **/README.md
        git commit -m "Render README.qmd files to README.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
